### ISSUE TITLE
Emacs freezing with dired-delight 

### ISSUE THREAD

**Issue by dasoju** [karthink/dired-delight#4]
After enabling dired-delight, when i open dired and go to a directory emacs freezes.
It does not happen when I don't enable dired-delight.

I ran profiler and did C-g when it freezes and generated the profiler report and I see that it is indeed due to dired-delight.
Please see the attached snapshot 
![Screenshot 2023-07-05 at 12 28 40 PM](https://github.com/karthink/dired-delight/assets/54728201/eba4b396-d45b-468d-a43e-2d995fe3fc6a)

**Comment by karthink** [comment]
Thanks for the profile, I'll look into it. Are you using it with dirvish?

**Comment by karthink** [comment]
Trying to reproduce.

1. Are you using it with dirvish?
2. Have you added `dired-delight-mode` to `dired-mode-hook`?

**Comment by dasoju** [comment]
I don't think so.
I installed dirvish from melpa, but iam not initializing the package in any
of my init el files.

**Comment by karthink** [comment]
@dasoju Have you added `dired-delight-mode` to `dired-mode-hook`?

**Comment by dasoju** [comment]
Yes, i did add it as part of the init, below is the snapshot
![image](https://github.com/karthink/dired-delight/assets/54728201/180cbdc4-688d-4e95-b164-7254cc1d6f4b)

**Comment by karthink** [comment]
Could you remove that line and add instead:

```elisp
(add-hook 'dired-mode-hook 'dired-delight-mode 90)
```

to the `:config` block, and let me know if it still freezes?  You'll have to check in a fresh Emacs session.

Also, if you don't add it to `dired-mode-hook` and instead turn on `dired-delight-mode` manually, does it still freeze?

**Comment by dasoju** [comment]
i didnt see the issue when i turned on manually 

I moved it to config section and still see the issue, please see the snapshot below
![image](https://github.com/karthink/dired-delight/assets/54728201/131df9ff-451c-4f3e-8367-3dc07c48883c)

**Comment by karthink** [comment]
I still haven't been able to reproduce this problem, but I pushed a potential fix on a hunch just now.  Could you test it again after updating?

**Comment by dasoju** [comment]
so far no hangs with new update !!
Thanks for the fix, I will keep watching, if I see the hang again, I will reopen
